export default {
    SIGN_IN: "SIGN_IN",
    SET_USERNAME: "SET_USERNAME",
    SET_ROOM_NUMBER: "SET_ROOM_NUMBER",
    VOLUME_TOGGLE: "VOLUME_TOGGLE",
    SWITCH_QUIZ: "SWITCH_QUIZ",
    LIGHT_CHECK: "LIGHT_CHECK"
} 