const questionTypes = [
    "General",
    "Two Part",
    "Three Part",
    "Four Part",
    "Five Part",
    "Multiple Part",
    "FTV",
    "Reference",
    "Situation"
];

const chapters = [{
    value: 1,
    label: 1,
    color: '#5243AA',
    isFixed: false,
    isDisabled: false
}, {
    value: 2,
    label: 2,
    color: '#5243AA',
    isFixed: false,
    isDisabled: false
}, {
    value: 3,
    label: 3,
    color: '#5243AA',
    isFixed: false,
    isDisabled: false
}, {
    value: 4,
    label: 4,
    color: '#5243AA',
    isFixed: false,
    isDisabled: false
}, {
    value: 5,
    label: 5,
    color: '#5243AA',
    isFixed: false,
    isDisabled: false
}, {
    value: 6,
    label: 6,
    color: '#5243AA',
    isFixed: false,
    isDisabled: false
}, {
    value: 7,
    label: 7,
    color: '#5243AA',
    isFixed: false,
    isDisabled: false
}, {
    value: 8,
    label: 8,
    color: '#5243AA',
    isFixed: false,
    isDisabled: false
}, {
    value: 9,
    label: 9,
    color: '#5243AA',
    isFixed: false,
    isDisabled: false
}, {
    value: 10,
    label: 10,
    color: '#5243AA',
    isFixed: false,
    isDisabled: false
}, {
    value: 11,
    label: 11,
    color: '#5243AA',
    isFixed: false,
    isDisabled: false
}, {
    value: 12,
    label: 12,
    color: '#5243AA',
    isFixed: false,
    isDisabled: false
}, {
    value: 13,
    label: 13,
    color: '#5243AA',
    isFixed: false,
    isDisabled: false
}, {
    value: 14,
    label: 14,
    color: '#5243AA',
    isFixed: false,
    isDisabled: false
}, {
    value: 15,
    label: 15,
    color: '#5243AA',
    isFixed: false,
    isDisabled: false
}, {
    value: 16,
    label: 16,
    color: '#5243AA',
    isFixed: false,
    isDisabled: false
}];
export { chapters, questionTypes }